name: Helm Charts Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run chart-releaser
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          dependencies: bitnami,https://charts.bitnami.com/bitnami
          token: ${{ secrets.GITHUB_TOKEN }}
